### ISSUE TITLE
How to do proper spoiler tags?

### ISSUE THREAD

**Issue by dessalines** [markdown-it/markdown-it-container#30]
I see the standard for spoiler tags is:
```
>!multi   
line  
spoiler  
line !<
```

or `>! spoiler !<`

According to both reddit and https://meta.stackexchange.com/questions/1191/add-markdown-support-for-hidden-until-you-click-text-aka-spoilers . Has anyone used this container to make this yet?

**Comment by puzrin** [comment]
This plugin uses fenced marking. Markup from link uses side marking. Those are different.

**Comment by dessalines** [comment]
So markdown-it currently has no support for any of the most popular implementations of spoiler tags?

**Comment by puzrin** [comment]
Default package supports only things described in commonmark spec + some github extensions. Everything else should be done via plugins. You may try to search one in npm or do your own, based on blockquote.

**Comment by KyleMit** [comment]
You can do it with the [markdown-it-spoiler](https://www.npmjs.com/package/markdown-it-spoiler) plugin, which has a slightly unconventional syntax compared to [other implementations](https://meta.stackexchange.com/a/72878/209031), but works just fine.  

Here's how you'd use it:

```
!!Spoiler!!
```

It probably diverges from other implementations because it's easier to borrow from other markdown it plugins that use pairs of special chars like [`++inserted++`](https://github.com/markdown-it/markdown-it-ins) or [`==marked==`](https://github.com/markdown-it/markdown-it-mark)
